version: '3.3'
services:
  db:
    image: mariadb:11
    ports:
      - "3306:3306"
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--max-allowed-packet=100M' ]
    environment:
      - MYSQL_DATABASE=indieverse
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
  indieverse:
    image: goshenkata123/indieverse:v3
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db 
    depends_on:
      - db
